services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iot101-api
    restart: always
    env_file:
      - .env
    ports:
      - "4100:4000"
    networks:
      - mqtttest
    depends_on:
      - db
      - mqtt-broker

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - mqtttest
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: iot-postgres

    networks:
      - mqtttest

networks:
  mqtttest:
    name: mqtttest
volumes:
  data: ~
